<?php
return array (
  'con_acc.facebook' => 'Facebook',
  'con_acc.github' => 'GitHub',
  'con_acc.google' => 'Google',
  'con_acc.linkedin' => 'Linkedin',
  'con_acc.microsoft' => 'Microsoft',
  'con_acc.nick_trakt' => 'Trakt',
  'con_acc.th_amazon' => 'Amazon',
  'con_acc.th_battlenet' => 'Battle.net',
  'con_acc.th_deviantart' => 'DeviantArt',
  'con_acc.th_discord' => 'Discord',
  'con_acc.th_dropbox' => 'Dropbox',
  'con_acc.th_instagram' => 'Instagram',
  'con_acc.th_pinterest' => 'Pinterest',
  'con_acc.th_reddit' => 'Reddit',
  'con_acc.th_tumblr' => 'Tumblr',
  'con_acc.th_twitch' => 'Twitch',
  'con_acc.twitter' => 'Twitter',
  'con_acc.yahoo' => 'Yahoo',
);