<?php
return array (
  'custom_bb_code_output.actor' => '',
  'custom_bb_code_output.br' => '',
  'custom_bb_code_output.charge' => '',
  'custom_bb_code_output.container' => '',
  'custom_bb_code_output.director' => '',
  'custom_bb_code_output.fs_custom_msg' => '',
  'custom_bb_code_output.fs_word_highlight' => '',
  'custom_bb_code_output.fsbunny' => '',
  'custom_bb_code_output.gallery' => '',
  'custom_bb_code_output.genre' => '',
  'custom_bb_code_output.group' => 'The information of group would appear here.',
  'custom_bb_code_output.imath' => '',
  'custom_bb_code_output.locked' => '',
  'custom_bb_code_output.math' => '',
  'custom_bb_code_output.movie' => '',
  'custom_bb_code_output.plot' => '',
  'custom_bb_code_output.poster' => '',
  'custom_bb_code_output.product' => '',
  'custom_bb_code_output.release' => '',
  'custom_bb_code_output.runtime' => '',
  'custom_bb_code_output.xen_word_highlight' => '',
);