<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0e5ec44b08ee01e3c8de87ec2b867eca
{
    public static $files = array (
        'b067bc7112e384b61c701452d53a14a8' => __DIR__ . '/..' . '/mtdowling/jmespath.php/src/JmesPath.php',
        '8a9dc1de0ca7e01f3e08231539562f61' => __DIR__ . '/..' . '/aws/aws-sdk-php/src/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'League\\Flysystem\\AwsS3v3\\' => 25,
        ),
        'J' => 
        array (
            'JmesPath\\' => 9,
        ),
        'A' => 
        array (
            'Aws\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'League\\Flysystem\\AwsS3v3\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem-aws-s3-v3/src',
        ),
        'JmesPath\\' => 
        array (
            0 => __DIR__ . '/..' . '/mtdowling/jmespath.php/src',
        ),
        'Aws\\' => 
        array (
            0 => __DIR__ . '/..' . '/aws/aws-sdk-php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0e5ec44b08ee01e3c8de87ec2b867eca::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0e5ec44b08ee01e3c8de87ec2b867eca::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
