<?php
return array (
  'custom_bb_code_title.actor' => 'TMDB actor',
  'custom_bb_code_title.br' => 'New Line',
  'custom_bb_code_title.charge' => 'Charge',
  'custom_bb_code_title.container' => 'TMDb container',
  'custom_bb_code_title.director' => 'TMDb director',
  'custom_bb_code_title.fs_custom_msg' => '[FS] Media Tags Custom message',
  'custom_bb_code_title.fs_word_highlight' => 'Highlight in red',
  'custom_bb_code_title.fsbunny' => 'Bunny BBCode',
  'custom_bb_code_title.gallery' => 'Gallery embed',
  'custom_bb_code_title.genre' => 'TMDb genre',
  'custom_bb_code_title.group' => 'Embed groups',
  'custom_bb_code_title.imath' => 'Inline math',
  'custom_bb_code_title.locked' => 'Hide Content and show preview with image',
  'custom_bb_code_title.math' => 'Block math',
  'custom_bb_code_title.movie' => 'TMDb movie',
  'custom_bb_code_title.plot' => 'TMDb plot',
  'custom_bb_code_title.poster' => 'TMDb poster container',
  'custom_bb_code_title.product' => 'Product embed',
  'custom_bb_code_title.release' => 'TMDb release date',
  'custom_bb_code_title.runtime' => 'TMDb runtime',
  'custom_bb_code_title.xen_word_highlight' => 'Highlight in red',
);