<?php
return array (
  'custom_bb_code_desc.actor' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.br' => '',
  'custom_bb_code_desc.charge' => 'Charging users to view your content.',
  'custom_bb_code_desc.container' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.director' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.fs_custom_msg' => 'Add custom message for media tags',
  'custom_bb_code_desc.fs_word_highlight' => 'Highlight block words in red using bbcode',
  'custom_bb_code_desc.fsbunny' => '',
  'custom_bb_code_desc.gallery' => 'BB code for displaying gallery media items and albums.',
  'custom_bb_code_desc.genre' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.group' => 'Display specific group information.',
  'custom_bb_code_desc.imath' => '',
  'custom_bb_code_desc.locked' => 'first image if exist else default image will be show on preview',
  'custom_bb_code_desc.math' => '',
  'custom_bb_code_desc.movie' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.plot' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.poster' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.product' => 'BB code for displaying products.',
  'custom_bb_code_desc.release' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.runtime' => 'For formatting old XF1 TMDb movie threads',
  'custom_bb_code_desc.xen_word_highlight' => 'Highlight banned words in red using bbcode.',
);