<?php
return array (
  'custom_bb_code_example.actor' => '',
  'custom_bb_code_example.br' => '',
  'custom_bb_code_example.charge' => '[CHARGE=5]It costs 5 credits to see this text.[/CHARGE]',
  'custom_bb_code_example.container' => '',
  'custom_bb_code_example.director' => '',
  'custom_bb_code_example.fs_custom_msg' => '',
  'custom_bb_code_example.fs_word_highlight' => '',
  'custom_bb_code_example.fsbunny' => '[fsbunny=libarayId]videoId[/fsbunny]',
  'custom_bb_code_example.gallery' => '[GALLERY=media, X]Gallery BB Code[/GALLERY]',
  'custom_bb_code_example.genre' => '',
  'custom_bb_code_example.group' => '[GROUP]123[/GROUP]',
  'custom_bb_code_example.imath' => '',
  'custom_bb_code_example.locked' => '[locked=15] some content [/locked]',
  'custom_bb_code_example.math' => '',
  'custom_bb_code_example.movie' => '',
  'custom_bb_code_example.plot' => '',
  'custom_bb_code_example.poster' => '',
  'custom_bb_code_example.product' => '[PRODUCT=product, X]Product BB Code[/PRODUCT]',
  'custom_bb_code_example.release' => '',
  'custom_bb_code_example.runtime' => '',
  'custom_bb_code_example.xen_word_highlight' => '',
);